### ISSUE TITLE
can't run test file on windows platform.

### ISSUE THREAD

**Issue by zilongshanren** [AlokSwaminathan/competitive-programming-tester-cli#1]
![image](https://github.com/AlokSwaminathan/competitive-programming-tester-cli/assets/785541/8d590d2e-6dd5-4417-8289-486be8b59318)

I have put my load_repayment_silver_jan20.cpp in the current directory, but I can't get it compiled.

Any help would be appreciated. thanks.

**Comment by AlokSwaminathan** [comment]
you can pass a local path to --file, so since you are in the directory you could try 
`cp-tester.exe run loan_repayment_silver_jan20 --file load_repayment_silver_jan20.cpp`

Also, I'm not sure if this is intentional but I'm not sure if the file name is spelled right, since the file name you are passing is "load_repayment_silver_jan20.cpp" which has "load" not "loan"

It could also be that the issue here is that in your absolute path the start where it says "c:" needs to be capitalized to be "C:"
Not totally sure though. Let me know if the error persists.

**Comment by zilongshanren** [comment]
The file name is a typo:

![image](https://github.com/AlokSwaminathan/competitive-programming-tester-cli/assets/785541/c1104519-048b-473d-bc48-f3ee24b587e5)


I use the `ls` command to list all the files in current directory, you can get the info from the picture.

**Comment by zilongshanren** [comment]
I guess the `cp-tester` program doesn't parse the file path correctly on windows platform.  From the error msg, it always complains  the same path is not a file...

**Comment by AlokSwaminathan** [comment]
Sorry for the issue, thanks for bringing it to my attention, I should be able to fix it soon. My main programming machines are mac and linux, so i hadn't done much windows testing. I tried to stay OS agnostic with file paths through using PathBuf, but something must have gone wrong.

**Comment by AlokSwaminathan** [comment]
trying this on a windows machine I can run the test and it compiles fine, but runs into another issue with spawning the thread to run the test, so that is something i will have to fix

I think the issue might instead lie with the compiler you are using "cc1plus.exe" which might be adding the extra slash and messing things up since it seems to work fine for me using both local and absolute paths

**Comment by zilongshanren** [comment]
> trying this on a windows machine I can run the test and it compiles fine, but runs into another issue with spawning the thread to run the test, so that is something i will have to fix
> 
> I think the issue might instead lie with the compiler you are using "cc1plus.exe" which might be adding the extra slash and messing things up since it seems to work fine for me using both local and absolute paths

I don't know why the `cp-tester` exec seek for the program `cc1plus.exe`, it seems that I install mingw32 on my machine and there is a `cc1plus.exe` in the PATH. 

I will try to figure it out why this happens.

thanks for your time.

**Comment by AlokSwaminathan** [comment]
> > trying this on a windows machine I can run the test and it compiles fine, but runs into another issue with spawning the thread to run the test, so that is something i will have to fix
> 
> > 
> 
> > I think the issue might instead lie with the compiler you are using "cc1plus.exe" which might be adding the extra slash and messing things up since it seems to work fine for me using both local and absolute paths
> 
> 
> 
> I don't know why the `cp-tester` exec seek for the program `cc1plus.exe`, it seems that I install mingw32 on my machine and there is a `cc1plus.exe` in the PATH. 
> 
> 
> 
> I will try to figure it out why this happens.
> 
> 
> 
> thanks for your time.

Ok sounds good. Regardless, there seems to be an issue with how std::Command works on windows since it runs without a shell there are some issues with running the tests once the code has been compiled. Unfortunately my windows machine is only at home so it's not easy for me to test, but I'll see if I can get a patch out for that today. If possible, if you are on a windows machine, I would recommend WSL2, so you can have a Linux command line which is useful overall and should also solve any issues with cp-tester for now

**Comment by AlokSwaminathan** [comment]
I've fixed all(hopefully) the windows errors, and on my windows device tests work on CPP, C, Java, and Python files.
